### ISSUE TITLE
Cannot run example code

### ISSUE THREAD

**Issue by staminna** [Ayms/node-dom#3]
$ node simple.js
/project/node_modules/node-dom/lib/dom.js:6
	Context = process.binding('evals').Context,
	                  ^

Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/Applications/MAMP/htdocs/wit.ai/project/node_modules/node-dom/lib/dom.js:6:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/wit.ai/project/simple.js:2:11)
    at Module._compile (module.js:434:26)

**Comment by Ayms** [comment]
I don't remember exactly why this line is there but apparently Context=process.binding('evals').Context is of no use, then please try to remove it and I will update the repo accordingly

**Comment by staminna** [comment]
I removed the line and it went down further until
$ node simple.js
/project/node_modules/node-dom/lib/browser/index.js:1373
	get id(val) {
	      ^^^^^

SyntaxError: Getter must not have any formal parameters.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/project/node_modules/node-dom/lib/dom.js:6:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by Ayms** [comment]
Typo in the code, strange that it did not show up before, replace get id(val) by get id()

**Comment by staminna** [comment]
Hi Amys, thanks for quick reply.
There is also a missing dependency for imagemagik.
$ node simple.js

   Error: Cannot find module 'imagemagick'
.. npm install imagemagick

imagemagick@0.1.3 node_modules/imagemagick
$ node simple.js
/project/node_modules/node-dom/lib/browser/html.js:63
			set selectedIndex() {},
			                 ^^

SyntaxError: Setter must have exactly one formal parameter.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/project/node_modules/node-dom/lib/browser/index.js:2203:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by Ayms** [comment]
Sorry for all these errors, the code was working well before but now some things do not parse any longer.

Here you could remove set selectedindex() {} which seems of no use or replace by set selectedindex(var){}

Maybe you could correct yourself all those small mistakes and send me everything at the end

**Comment by staminna** [comment]
I have cloned the repository locally, and I can create a patch once it is working.
I went further on the code doing the same for every instance of errors such as above, deleting where "Setter must have exactly one formal parameter" until 

'$ node simple.js
/Applications/MAMP/htdocs/wit.ai/project/node_modules/node-dom/lib/browser/htmltodom.js:14
if (parser.ParseHtml) {
          ^

TypeError: Cannot read property 'ParseHtml' of null
    at Object.<anonymous> (/project/node_modules/node-dom/lib/browser/htmltodom.js:14:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (i/project/node_modules/node-dom/lib/dom.js:13:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)'

**Comment by Ayms** [comment]
Again, I can be of little help here, you should try to solve everything by yourself.

try {
	parser = require('htmlparser');
} catch (ee) {
	try {
		parser = require('node-htmlparser/lib/node-htmlparser');
	} catch (ee2) {	}
};

You should install htmlparser and imagemagick, see the complementary modules in install (don't remember why htmlparser is not listed here)

**Comment by staminna** [comment]
After installing imagemagick, htmlparser and tav and removing the above lines in the code, it shows command line options. Next I'll try to make it work with node-bot. Thanks!

**Comment by Ayms** [comment]
Great, node-bot should not cause those problems, don't hesitate to email me and/or update me about what you are doing if you like (I am curious, yes!) and thanks if you can PR your changes here so I can update the repo.

**Comment by staminna** [comment]
This will be my first time, I must setup github. Let me test this first then I'll do a pull request once I am sure it works as expected. Will let you know. 
Thank you.

**Comment by AaronGoldsmith1** [comment]
All of the aforementioned issues still exist in the module.  There are 4 other instances of a useless setter function `set value(val) {},` in node-dom/lib/browser/html.js.  I followed the above steps as well, and now see the command line options.  It's too bad, this module would have really come in handy.  I'll try making a pull request...

**Comment by Ayms** [comment]
Thanks I have merged your PR, indeed the code is old and needs some updates
